### ISSUE TITLE
Inline-block and white space in the grid

### ISSUE THREAD

**Issue by scottmontminy** [csswizardry/inuit.css#170]
I hope to raise this as a new issue for clarity sake, but my apologies upfront because I know this has been discussed all over the place related to inuit.css [here](https://github.com/csswizardry/inuit.css/issues/164) and [here](https://github.com/csswizardry/csswizardry-grids/commit/744d4b23c9d2b77d605b5991e54a397df72e0688) and [elsewhere](https://github.com/yui/yui3/pull/468).

In regards to using inline-block for the grid system, do we suspect that the solution of [commenting the whitespace between grid elements](https://github.com/csswizardry/csswizardry-grids/commit/744d4b23c9d2b77d605b5991e54a397df72e0688) is the long-term solution for inuit.css?

The commenting solution is no doubt a robust solution (or removing the whitespace altogether). No argument there and I'm thankful for the solution because using inline-block for grid elements is simply awesome.

However, the commenting solution does make our grid dependent on HTML formatting - which although semantically valid seems like it will present it's fair share of challenges when working with a team of developers and/or using the grid on repeating regions generated from a database. Basically, I'm reluctant to use the grid system with this dependency on a production site if this is the long-term solution.

Again, sorry for the redundancy. Amidst all the issue threads I can find on this topic, I'm a little confused about the short-term vs. long-term ramifications. Thanks.

**Comment by jmp909** [comment]
hi.. i was struggling with this a bit. i wanted to make a grid of articles that are split into 2 columns. i had to nest another grid inside my main grid http://pastebin.com/kCYXa8ZA
 
because i can't see, to put

```<div class="grid">
<!--
{% for item in vehicles %}
/--><article>
     <div class="grid__item">...</div><!--
/--><div class="grid__item">...</div><!--
/--></article><!--
{% endfor %}
-->
</div>
```

any suggestions much appreciated.

enjoying following your work. thanks.

j

**Comment by graste** [comment]
See [my comment above](https://github.com/csswizardry/inuit.css/issues/170#issuecomment-29761759) – in addition to ```{% spaceless %}``` you can use `-` as a whitespace modifier in twig, e.g. ```{%- for … -%}``` – see [twig whitespace control docs](http://twig.sensiolabs.org/doc/templates.html#whitespace-control) for details.
