### ISSUE TITLE
Invalid US-ASCII character "\xE2"

### ISSUE THREAD

**Issue by sjelfull** [csswizardry/inuit.css#270]
I'm getting this error in most of the framework files:
    `error src/sass/style.scss (Line 11 of src/sass/inuit.css/generic/_reset.scss: Invalid US-ASCII character "\xE2")`

It the character `’`, among others, that's causing the trouble.

**Comment by worldofchris** [comment]
+1 for @marcbachmann solution.  Worked for me.  I was running an ansible playbook local_action from a Jenkins Job.  Added those exports to the Jenkins job and it worked.  Many Thanks.

**Comment by wungqiang** [comment]
thx to @marcbachmann , works for me, this problem appears after my installing 'on my zsh' first

**Comment by marcbachmann** [comment]
Hehe. You're welcome. Apparently it's a common problem among mac users.

**Comment by jorgvm** [comment]
If on OSX and you recently installed ZSH, uninstall helps :)

**Comment by lucamolteni** [comment]
Thank you @marcbachmann your solution solved my problem on Yosemite with oh-my-zsh.

**Comment by JamieMason** [comment]
In the following forks I've removed any characters which trigger this exception, then bumped and tagged a point release. I haven't created pull requests, but if these changes look acceptable @csswizardry then I can go ahead and do that.

+ [base.headings](https://github.com/JamieMason/base.headings/compare/inuitcss:master...master)
+ [base.images](https://github.com/JamieMason/base.images/compare/inuitcss:master...master)
+ [base.page](https://github.com/JamieMason/base.page/compare/inuitcss:master...master)
+ [objects.buttons](https://github.com/JamieMason/objects.buttons/compare/inuitcss:master...master)
+ [objects.flag](https://github.com/JamieMason/objects.flag/compare/inuitcss:master...master)
+ [objects.media](https://github.com/JamieMason/objects.media/compare/inuitcss:master...master)
+ [objects.tables](https://github.com/JamieMason/objects.tables/compare/inuitcss:master...master)
+ [settings.defaults](https://github.com/JamieMason/settings.defaults/compare/inuitcss:master...master)
+ [tools.mixins](https://github.com/JamieMason/tools.mixins/compare/inuitcss:master...master)
+ [tools.responsive](https://github.com/JamieMason/tools.responsive/compare/inuitcss:master...master)
+ [trumps.print](https://github.com/JamieMason/trumps.print/compare/inuitcss:master...master)
+ [trumps.spacing-responsive](https://github.com/JamieMason/trumps.spacing-responsive/compare/inuitcss:master...master)
+ [trumps.widths-responsive](https://github.com/JamieMason/trumps.widths-responsive/compare/inuitcss:master...master)

Thanks a lot.

**Comment by maximaldesign** [comment]
`@charset "UTF-8";` at the very beginning of every file which is included and the main file resolved the issue even using CodeKit. Thanks to @kleinfreund

**Comment by stephencoe** [comment]
You can tell compass to force UTF-8 by adding the option `Encoding.default_external = 'utf-8'` to the config.rb

if you are using grunt-compass it can be added through the options

```
{
  options: {
    raw: 'Encoding.default_external = \'utf-8\'\n'
  }
}
```

[source](http://blog.pixelastic.com/2014/09/06/compass-utf-8-encoding-on-windows/)

**Comment by manjang** [comment]
Most ASCII errors in SASS arise from copying the text somewhere with different encoding. If you have such problems try hand coding (typing) instead of copy and paste.

**Comment by lora-palmer** [comment]
blah blah blah
