### ISSUE TITLE
You suck please die

### ISSUE THREAD

**Issue by YemSalat** [csswizardry/inuit.css#333]
You are doing useless work. The faster you stop this nonsense the better for all of us.

**Comment by corysimmons** [comment]
Please close as [no jsFiddle](https://github.com/csswizardry/inuit.css/blob/master/CONTRIBUTING.md#bugs-and-issues) was provided.

**Comment by csswizardry** [comment]
This project has moved: [github.com/inuitcss](https://github.com/inuitcss).

Please feel free to reopen there and I’ll see if I can look into installing the `dev-suicide` Gem.

**Comment by nouveller** [comment]
Firstly, what a pointless comment to make. This helps no one, the community, @csswizardry nor yourself. All you've done is make yourself look immature and ignorant. Harry's work is far from useless, it benefits the CSS community as a whole.

This is not the place for trolls.

**Comment by Wakkos** [comment]
Why you closed this @csswizardry? You are still alive, the bug is not solved. =P

**Comment by Quader** [comment]
![That escalated quickly](http://www.xboxoneforums.net/forum/attachments/790d1389388275-what-s-your-day-job-escalated-quickly.jpg)

**Comment by techytuppers** [comment]
What a knob.

**Comment by deserted** [comment]
get's even funnier after you look at the CSS in his repos...

**Comment by Quader** [comment]
@deserted xD

**Comment by YemSalat** [comment]
The issue still occurs for me.

@deserted there is no css in my repos.

**Comment by corysimmons** [comment]
<img src="http://i.imgur.com/xUVW1xD.png" width="200">
