### ISSUE TITLE
How can it be BEM  *&*  OOCSS ??

### ISSUE THREAD

**Issue by fabm22** [csswizardry/inuit.css#337]
Hi there,

For what I've been gathering the two methodologies BEM & OOCSS overlap... How exactly can inuit.css be **both** at same time ? 

Could you please enlight me a little ? Thanks a lot.

**Comment by kleinfreund** [comment]
Why is that contradictory to you? Only because inuit.css is based upon methodologies from BEM and OOCSS does not mean they cannot have both. Can you give an example where these conflict?

**Comment by unwiredbrain** [comment]
The way I see it, BEM and OOCSS are organisational system that try to solve different areas of the same problem.

- BEM is more about naming conventions and defining clear boundaries among pieces of content.
- OOCSS is more about defining common reusable patterns that can then be extended later on.

I don't see an overlapping problem there.
